# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4377607d1793ee7b9b02acda009c51983809c07e2f5877bcef29f577fb9ae99cdf704489f58ef25457330ac44a595ac0f8852c4d64fc282829b6c9f48473c681

test:
  secret_key_base: 8cffc7d4243109b308246fd2c605cc89ac36ccb8b2f7d3949c81e09735169f58b276035de1cfa6ca0c3e6e9451efb19eab08391f708c66ad3ca6ab05e7c46ace

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
